app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('project/', include('project.urls')),
    path('software/', include('software.urls')),
    path('accounts/', include('accounts.urls')),
    path('chatbot/', include('bot.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upload/urls.py
from django.urls import path

from upload.views import ImageCreateView

urlpatterns = [
    # path('logo/', ImageCreateView.as_view(), name='new-logo')
]

upload/models.py
from django.urls import reverse
from django.db import models

from io import BytesIO
from django.core.files import File
from PIL import Image

# Create your models here.
class Image(models.Model):
    title = models.CharField(("titulo"), max_length=50, unique=True)
    image = models.ImageField(("imagen"), upload_to='uploads/', blank=True, null=True)
    thumbnail = models.ImageField(upload_to='uploads/', blank=True, null=True)
    project = models.ForeignKey("project.Project",on_delete=models.CASCADE, related_name="images")
    is_logo = models.BooleanField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = ("Image")
        verbose_name_plural = ("Images")
        ordering = ("-id",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("Images_detail", kwargs={"pk": self.pk})
    
    def get_image(self):
        if self.image:
            return 'http://127.0.0.1:8000' + self.image.url
        return ''
            
    def get_thumbnail(self):
        if self.thumbnail:
            return 'http://127.0.0.1:8000' + self.thumbnail.url
        else:
            if self.image:
                self.thumbnail = self.make_thumbnail(self.image)
                self.save()

                return 'http://127.0.0.1:8000' + self.thumbnail.url
            else:
                return ''
    
    def make_thumbnail(self, image, size=(300, 200)):
        img = Image.open(image)
        img.convert('RGB')
        img.thumbnail(size)

        thumb_io = BytesIO()
        img.save(thumb_io, 'JPEG', quality=85)

        thumbnail = File(thumb_io, name=image.name)

        return thumbnail

upload/forms.py
from django import forms

from upload.models import Image

class ImageForm(forms.ModelForm):
    
    class Meta:
        model = Image
        fields = ("project","title","image","is_logo")
        
        labels = {
            "title":("Titulo de la imagen"),
            "is_logo": ("logo?")    
        }
        
        widgets = {
            "project": forms.TextInput(attrs={'style':'display:none'}),
            "title": forms.TextInput(attrs={'class':'form-control p-1'}),
            "is_logo": forms.CheckboxInput(attrs={})
        }

upload/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse

from upload.models import Image
from upload.forms import ImageForm

from project.models import Project

from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView

# Create your views here.
class ImageCreateView(CreateView):
    model = Image
    template_name = "upload/new.html"
    form_class = ImageForm
    
    def get_success_url(self):
        return reverse_lazy('list_image', kwargs={'pk': self.object.project.id})
    
    def get_context_data(self, **kwargs) -> dict[str, Project]:
        context = super().get_context_data(**kwargs)
        object = Project.objects.get(pk=self.kwargs['pk'])
        context["object"] = object
        return context
    
class ImageDetailView(DetailView):
    model = Image
    template_name = "upload/detail.html"
    
def delete_image(request):
    img = Image.objects.get(pk=request.POST.get('pk'))
    object = img.project
    img.delete()
    return reverse("detail", kwargs={'pk': object.id}) #render(request, 'project/detail.html', {'url': reverse("detail", kwargs={"pk": object.id })})


class ImageListView(ListView):
    model = Image
    template_name = "upload/list.html"
    
    def get_context_data(self, **kwargs) -> dict[str, object]:
        context = super().get_context_data(**kwargs)
        context["object_list"] = Image.objects.filter(project__id=self.kwargs['pk'])
        return context
    

templates/upload/detail.html
<div class="container" id="root">
    <img src="{{ image.get_image }}" alt="{{image.title}}" width="300" class="p-2">
        
    <form method="post" action="{% url "delete_image" %}" class="mt-3">
        {% csrf_token %}
        <input type="number" value="{{ image.id }}" name="pk" style="display:none;">
        
        <button type="submit" class="btn bg-primary-subtle p-2 mt-3" >
            <svg viewBox="0 0 24 24" fill="none" width="16" heigth="16" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M5.16565 10.1534C5.07629 8.99181 5.99473 8 7.15975 8H16.8402C18.0053 8 18.9237 8.9918 18.8344 10.1534L18.142 19.1534C18.0619 20.1954 17.193 21 16.1479 21H7.85206C6.80699 21 5.93811 20.1954 5.85795 19.1534L5.16565 10.1534Z" stroke="#000000" stroke-width="2"></path> <path d="M19.5 5H4.5" stroke="#000000" stroke-width="2" stroke-linecap="round"></path> <path d="M10 3C10 2.44772 10.4477 2 11 2H13C13.5523 2 14 2.44772 14 3V5H10V3Z" stroke="#000000" stroke-width="2"></path> </g></svg>
            Eliminar imagen
        </button>
    </form>
</div>

templates/upload/list.html
<div id="root">
<table class="table">
    <thead>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Usuario</th>
        <th scope="col">Ultima modificación</th>
        <th scope="col">Tamaño de archivo</th>
      </tr>
    </thead>
    <tbody>
    {% for obj in object_list %}
      <tr>
          <td>
              <div class="d-flex">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-folder-fill" viewBox="0 0 16 16">
                      <path d="M9.828 3h3.982a2 2 0 0 1 1.992 2.181l-.637 7A2 2 0 0 1 13.174 14H2.825a2 2 0 0 1-1.991-1.819l-.637-7a2 2 0 0 1 .342-1.31L.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3m-8.322.12q.322-.119.684-.12h5.396l-.707-.707A1 1 0 0 0 6.172 2H2.5a1 1 0 0 0-1 .981z"/>
                    </svg>
                    <p>
                        <a href="{% url 'detail' pk=obj.id %}">
                            {{ obj.title }}
                        </a>
                    </p>
                </div>
            </td>
            <th>
                <div>
                    <img src="{{ obj.get_image }}" width="52px" height="60px">
                </div>
            </th>
            <td>{{ obj.created_at }}</td>
        <td>1 kbs</td>
      </tr>
      
    {% endfor %}
    </tbody>
</table>
</div>

templates/upload/new.html
<style>
    .uploadContainer {
        border-radius: 10px;
        /* box-shadow: 4px 4px 30px rgba(0, 0, 0, .2); */
        /* display: flex;
        flex-direction: column;
        align-items: center; */
        /* justify-content: space-between; */
        position: relative;
        padding: 10px;
        gap: 5px;
        background-color: rgb(214, 182, 182);
      }
      
      .header {
        flex: 1;
        width: 100%;
        border: 2px dashed royalblue;
        border-radius: 10px;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
      }
      
      .header svg {
        height: 100px;
      }
      
      .header p {
        text-align: center;
        color: black;
      }
      
      .footer {
        
        width: 100%;
        height: 40px;
        padding: 8px;
        border-radius: 10px;
        cursor: pointer;
        display: flex;
        align-items: center;
        justify-content: flex-end;
        color: black;
        border: none;
      }
      
      .footer svg {
        height: 130%;
        fill: royalblue;
        background-color: rgba(70, 66, 66, 0.103);
        border-radius: 50%;
        padding: 2px;
        cursor: pointer;
        box-shadow: 0 2px 30px rgba(0, 0, 0, 0.205);
      }
      
      .footer p {
        flex: 1;
        text-align: center;
      }
    
    .upload {
        width: 100%;
        height: 300px;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .switch {
    --button-width: 3.5em;
    --button-height: 2em;
    --toggle-diameter: 1.5em;
    --button-toggle-offset: calc((var(--button-height) - var(--toggle-diameter)) / 2);
    --toggle-shadow-offset: 10px;
    --toggle-wider: 3em;
    --color-grey: #cccccc;
    --color-green: #4296f4;
    }

    .slider {
    display: inline-block;
    width: var(--button-width);
    height: var(--button-height);
    background-color: var(--color-grey);
    border-radius: calc(var(--button-height) / 2);
    position: relative;
    transition: 0.3s all ease-in-out;
    }

    .slider::after {
        content: "";
        display: inline-block;
        width: var(--toggle-diameter);
        height: var(--toggle-diameter);
        background-color: #fff;
        border-radius: calc(var(--toggle-diameter) / 2);
        position: absolute;
        top: var(--button-toggle-offset);
        transform: translateX(var(--button-toggle-offset));
        box-shadow: var(--toggle-shadow-offset) 0 calc(var(--toggle-shadow-offset) * 4) rgba(0, 0, 0, 0.1);
        transition: 0.3s all ease-in-out;
    }

    .switch input[type="checkbox"]:checked + .slider {
        background-color: var(--color-green);
    }

    .switch input[type="checkbox"]:checked + .slider::after {
        transform: translateX(calc(var(--button-width) - var(--toggle-diameter) - var(--button-toggle-offset)));
        box-shadow: calc(var(--toggle-shadow-offset) * -1) 0 calc(var(--toggle-shadow-offset) * 4) rgba(0, 0, 0, 0.1);
    }

    .switch input[type="checkbox"] {
        display: none;
    }

    .switch input[type="checkbox"]:active + .slider::after {
        width: var(--toggle-wider);
    }

    .switch input[type="checkbox"]:checked:active + .slider::after {
        transform: translateX(calc(var(--button-width) - var(--toggle-wider) - var(--button-toggle-offset)));
    }

    .upload{
        width: 100%;
        height: 200px;
        border: 2px dotted gray;
        border-radius: 5px;
        margin-top: 9px;
        justify-content: center;
        align-items: center;
        flex-direction: column;
 
    }

    .upload label{
        cursor: pointer;
        display: flex;
    }

    .upload svg{
        color: rgb(87, 85, 85);
    }

    .upload:hover{
        border: 2px dotted black;
    }


    .upload div{
        width: 50px;
        height: 50px;
        border-radius: 100%;
        background-color: rgb(194, 189, 189);;
        display: flex;
        justify-content: center;
        padding: 1px;
    }

</style>

<div id="root">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title h2" id="offcanvasRightLabel">Subir imagen</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <div class="card">
            <div class="card-body">
                <div class="container p-4">
                    <form hx-post="{% url "new_image" pk=object.id %}" enctype="multipart/form-data" hx-target="this" hx-swap="outerHTML">
                        {% csrf_token %}
                        <label for="" class="mb-1">Titulo de la imagen</label>
                        <input id="id_title" type="text" name="title" class="border form-control mb-2"> 
                        <div class="upload">
                            <img 
                                src="photo.png"  
                                alt=""  
                                id="id_img"
                                width="250px"
                            >
                            <label for="id_image" id="id_label">
                                <div>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-arrow-bar-up" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M8 10a.5.5 0 0 0 .5-.5V3.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 3.707V9.5a.5.5 0 0 0 .5.5m-7 2.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1-.5-.5"/>
                                    </svg>
                                </div>
                                Haz click para seleccionar una imagen
                                <p style="color: rgb(175, 175, 175);">PNG, JPG, GIF, hasta 10MB</p> 
                            </label>
                        </div>
                        <label class="switch mt-2">
                            <input type="checkbox" name="is_logo">
                            <span class="slider"></span>
                            <span class="">Esta imagen corresponde al LOGO del software</span>
                        </label>
                        <input id="id_project" type="text" name="project" style="display: none;" value="{{object.id}}"> 
                        <input id="id_image" type="file" name="image" accept="image/*" style="display: none;"> 
                        <div class="d-flex justify-content-between ">
                            <input type="submit" class="btn border p-2 mt-3 btn-primary" value="Subir imagen">
                            <button type="button" id="id_delete" class="btn d-flex mt-3 btn-sm align-items-center"  disabled="true">
                                <svg viewBox="0 0 24 24" fill="none" width="16" heigth="16" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M5.16565 10.1534C5.07629 8.99181 5.99473 8 7.15975 8H16.8402C18.0053 8 18.9237 8.9918 18.8344 10.1534L18.142 19.1534C18.0619 20.1954 17.193 21 16.1479 21H7.85206C6.80699 21 5.93811 20.1954 5.85795 19.1534L5.16565 10.1534Z" stroke="#000000" stroke-width="2"></path> <path d="M19.5 5H4.5" stroke="#000000" stroke-width="2" stroke-linecap="round"></path> <path d="M10 3C10 2.44772 10.4477 2 11 2H13C13.5523 2 14 2.44772 14 3V5H10V3Z" stroke="#000000" stroke-width="2"></path> </g></svg>
                                Descartar
                            </button>
                        </div>
                    
                    </form>
                </div>

            </div>
    
        </div>

    </div>
</div>


<script>
    var titleEl = document.getElementById('id_title')
    var imageEl = document.getElementById('id_image')
    const img = document.querySelector('#id_img')
    const textFile = document.querySelector("#id_text_file")
    const deleteBtn= document.querySelector("#id_delete")

    imageEl.addEventListener('change', e=> selectedFile(img, titleEl, e))

    deleteBtn.addEventListener('click', e=> deleteFile(img, e))

    const resizeImageToFitContainer = (img, container) => {
        const originalWidth = img.naturalWidth;
        const originalHeight = img.naturalHeight;

        const containerWidth = container.clientWidth;
        const containerHeight = container.clientHeight;

        
        const widthRatio = containerWidth / originalWidth;
        const heightRatio = containerHeight / originalHeight;
        
        const scale = Math.min(widthRatio, heightRatio);

        const newWidth = originalWidth * scale;
        const newHeight = originalHeight * scale;

        img.style.width = `${newWidth}px`;
        img.style.height = `${newHeight}px`;
        container.style.height = `${newHeight + 100}px`;
    }

    const selectedFile = (imgEl, helpText, env) =>{
        helpText.value = env.target.files[0].name
        
        if(env.target.files[0]){
            deleteBtn.disabled = false;
            document.getElementById('id_label').style.display = "none";
            
            const reader = new FileReader()
            reader.onload = (env)=>{
                imgEl.src = env.target.result
            }
            reader.readAsDataURL(env.target.files[0])
        }
    }

    
    const deleteFile = (imgEl, helpText)=>{
        imgEl.src = '';
        titleEl.value = "";
        document.getElementById('id_label').style.display = "block";
        helpText.textContent = "No hay un archivo";

    }
    

</script>